-- FitFusion Supabase Schema
-- Run this in your Supabase SQL Editor to initialize the database

-- 1. Create the Users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Create the Outfit Preferences table
CREATE TABLE IF NOT EXISTS outfit_prefs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  occasion TEXT,
  style TEXT,
  colors TEXT, -- JSON string
  budget TEXT,
  gender TEXT,
  extras TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Create the Saved Looks table
CREATE TABLE IF NOT EXISTS saved_looks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  look_data JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_outfit_prefs_user_id ON outfit_prefs(user_id);
CREATE INDEX IF NOT EXISTS idx_saved_looks_user_id ON saved_looks(user_id);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at);
CREATE INDEX IF NOT EXISTS idx_outfit_prefs_created_at ON outfit_prefs(created_at);
CREATE INDEX IF NOT EXISTS idx_saved_looks_created_at ON saved_looks(created_at);

-- Note: Row Level Security (RLS) is DISABLED by default. 
-- It is left disabled because the Node.js backend manages data access and security.
