-- Supabase SQL Schema for FitFusion
-- Run this in your Supabase SQL Editor to create the tables

-- Users table
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Outfit preferences table
CREATE TABLE IF NOT EXISTS outfit_prefs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  occasion TEXT,
  style TEXT,
  colors TEXT, -- JSON string
  budget TEXT,
  gender TEXT,
  extras TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE outfit_prefs ENABLE ROW LEVEL SECURITY;

-- Create policies for users table
CREATE POLICY "Users can view own profile" ON users
  FOR SELECT USING (auth.uid() = id::text);

CREATE POLICY "Users can insert own profile" ON users
  FOR INSERT WITH CHECK (auth.uid() = id::text);

CREATE POLICY "Users can update own profile" ON users
  FOR UPDATE USING (auth.uid() = id::text);

-- Create policies for outfit_prefs table
CREATE POLICY "Users can view own outfit preferences" ON outfit_prefs
  FOR SELECT USING (auth.uid() = user_id::text);

CREATE POLICY "Users can insert own outfit preferences" ON outfit_prefs
  FOR INSERT WITH CHECK (auth.uid() = user_id::text);

CREATE POLICY "Users can update own outfit preferences" ON outfit_prefs
  FOR UPDATE USING (auth.uid() = user_id::text);

CREATE POLICY "Users can delete own outfit preferences" ON outfit_prefs
  FOR DELETE USING (auth.uid() = user_id::text);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);
CREATE INDEX IF NOT EXISTS idx_outfit_prefs_user_id ON outfit_prefs(user_id);
CREATE INDEX IF NOT EXISTS idx_users_created_at ON users(created_at);
CREATE INDEX IF NOT EXISTS idx_outfit_prefs_created_at ON outfit_prefs(created_at);
